### ISSUE TITLE
How to crop multiple images in pageView?

### ISSUE THREAD

**Issue by burakcbdn** [lykhonis/image_crop#64]
I want to implement multiple cropping feature, is there a way to do it? (like instagram create post section)

**Comment by burakcbdn** [comment]
resolved by using list of crop keys.

**Comment by moo-kesh** [comment]
Hi @burakcbdn , can you please explain the solution a bit more?
I'm trying to use multiple crop views in a PageView, but when I try to crop all images then some of them are not being cropped because the Crop widget is not setup yet!
   if (area == null) {
      // cannot crop, widget is not setup
      return;
    }
How can I use some default values for scale and area?

**Comment by burakcbdn** [comment]
@mueksh-b I created list for holding state keys for crop. Everytime users selects new image I created a new crop key and added it to the list.
